version: "3.9"

services:
  app:
    container_name: markoslav
    build: .
    depends_on:
      - postgres
    ports:
      - "8088:8080"
    networks:
      - local
    env_file:
      - .env
    restart: on-failure
  postgres:
    container_name: markoslav_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - local
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: on-failure

volumes:
  postgres-data:

networks:
  local:
    driver: bridge